name = "lab62"
main = "worker/index.ts"
compatibility_date = "2025-10-01"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_id = "lab62-db"

[[kv_namespaces]]
binding = "KV_NAMESPACE"
id = "lab62-kv"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "lab62-r2"

[vars]
GOOGLE_AI_STUDIO_API_KEY = "${GOOGLE_AI_STUDIO_API_KEY}"
JWT_SECRET = "${JWT_SECRET}"
WEBHOOK_SECRET = "${WEBHOOK_SECRET}"
